version: '3.8'
services:
  fast-n-foodious-ms-produto:
    restart: unless-stopped
    image: ottero/fast-n-foodious-ms-produto:latest
    container_name: fast-n-foodious-ms-produto
    env_file:
      - ./envs/${NODE_ENV:-prod}.env
    ports:
      - 3000:3000
    depends_on:
      - mysql-produto
    networks:
      - fast-n-foodious-network
    environment:
      MYSQL_PORT: 3306
      MYSQL_HOST: mysql-produto
  fast-n-foodious-ms-pedido:
    restart: unless-stopped
    image: ottero/fast-n-foodious-ms-pedido:latest
    container_name: fast-n-foodious-ms-pedido
    env_file:
      - ./envs/${NODE_ENV:-prod}.env
    ports:
      - 3001:3000
    depends_on:
      - mysql-pedido
    networks:
      - fast-n-foodious-network
    environment:
      MYSQL_PORT: 3307
      MYSQL_HOST: mysql-pedido
  fast-n-foodious-ms-pagamento:
    restart: unless-stopped
    image: ottero/fast-n-foodious-ms-pagamento:latest
    container_name: fast-n-foodious-ms-pagamento
    env_file:
      - ./envs/${NODE_ENV:-prod}.env
    ports:
      - 3002:3000
    depends_on:
      # - mysql-pagamento
      - mongodb
    networks:
      - fast-n-foodious-network
    environment:
      # MYSQL_PORT: 3308
      # MYSQL_HOST: mysql-pagamento
      DATABASE_ENGINE: $DATABASE_ENGINE
      DOCUMENTDB_URI: $DOCUMENTDB_URI
  mysql-produto:
    image: mysql:8.0
    container_name: mysql-produto    
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: $MYSQL_USER
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    volumes:
      - ./scripts/schema:/docker-entrypoint-initdb.d
      - mysql-data-produto:/data/db
    networks:
      - fast-n-foodious-network
  mysql-pedido:
    image: mysql:8.0
    container_name: mysql-pedido    
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: $MYSQL_USER
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    volumes:
      - ../fast-n-foodious-ms-pedido/scripts/schema:/docker-entrypoint-initdb.d
      - mysql-data-pedido:/data/db
    networks:
      - fast-n-foodious-network
  # mysql-pagamento:
  #   image: mysql:8.0
  #   container_name: mysql-pagamento    
  #   restart: unless-stopped
  #   environment:
  #     MYSQL_PASSWORD: $MYSQL_PASSWORD
  #     MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  #     MYSQL_ROOT_HOST: '%'
  #     MYSQL_USER: $MYSQL_USER
  #     MYSQL_DATABASE: $MYSQL_DATABASE
  #     MYSQL_TCP_PORT: 3308
  #   ports:
  #     - 3308:3308
  #   volumes:
  #     - ./scripts/schema:/docker-entrypoint-initdb.d
  #     - mysql-data-pagamento:/data/db
  #   networks:
  #     - fast-n-foodious-network      
  mongodb:
    container_name: mongodb
    image: mongo:7.0.5
    ports:
      - '27017:27017'
    environment:
      DOCUMENTDB_URI: $DOCUMENTDB_URI
      MONGO_INITDB_ROOT_USERNAME: $DOCUMENTDB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DOCUMENTDB_PASSWORD
      MONGO_INITDB_DATABASE: $DOCUMENTDB_DATABASE
    volumes:
      - mongo-data-pagamento:/data/mongodb
    networks:
      - fast-n-foodious-network
volumes:
  mysql-data-produto:
  mysql-data-pedido:
  # mysql-data-pagamento:
  mongo-data-pagamento:
networks:
  fast-n-foodious-network:
    driver: bridge