apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-n-foodious-ms-produto
spec:
  selector:
    matchLabels:
      app: fast-n-foodious-ms-produto
  template:
    metadata:
      labels:
        app: fast-n-foodious-ms-produto
    spec:
      containers:
      - name: fast-n-foodious-ms-produto
        image: ottero/fast-n-foodious-ms-produto:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            port: 3000
            path: /api
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            port: 3000
            path: /api
          initialDelaySeconds: 40
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: fast-n-foodious-ms-produto-env
        env:
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fast-n-foodious-ms-produto-secret
                key: MYSQL_PASSWORD
          - name: SERVER_PORT
            valueFrom:
              configMapKeyRef:
                name: fast-n-foodious-ms-produto-env
                key: SERVER_PORT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-produto
spec:
  selector:
    matchLabels:
      app: mysql-produto
  template:
    metadata:
      labels:
        app: mysql-produto
    spec:
      containers:
      - name: mysql-produto
        image: mysql:8.0
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
        ports:
          - containerPort: 3306
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
          - configMapRef:
              name: fast-n-foodious-ms-produto-env
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fast-n-foodious-ms-produto-secret
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: fast-n-foodious-ms-produto-secret
                key: MYSQL_PASSWORD
        volumeMounts:
          - name: mysql-init
            mountPath: /docker-entrypoint-initdb.d
          - name: fast-n-foodious-ms-produto-volume
            mountPath: /var/lib/mysql
      volumes:
        - name: fast-n-foodious-ms-produto-volume
          persistentVolumeClaim:
            claimName: fast-n-foodious-ms-produto-pvc
        - name: mysql-init
          configMap:
            name: mysql-produto-env
            items:
              - key: init.sql
                path: 1-init.sql
              - key: populate.sql
                path: 2-populate.sql
